### ISSUE TITLE
VCEP Tracker: Alert and Priority Tab enhancements

### ISSUE THREAD

**Issue by dazzariti** [clingen-data-model/clinvar-google-sheets#10]
Feedback discussed with Broad team on Feb 26 with Broad curation team

High priority
- [x] Remove color coding on priority tab based on CvC annotation formatting rules
- [x] Change symbol for “NonContributory” CvC annotation, replace exclamation point with $

**Comment by dazzariti** [comment]
Determine what * signifies

**Comment by toneillbroad** [comment]
Ryan these are the tasks we discussed in the zoom recording on June 14th.

**Comment by RyanFWebb** [comment]
Completed on June 16th.

**Comment by larrybabb** [comment]
@dazzariti please verify these 2 items are working as expected in one or more of the vcep sheets. closs if they are. work with Ryan if there's any issues.

**Comment by RyanFWebb** [comment]
> Determine what * signifies

* Signifies an outdated curation.

**Comment by dazzariti** [comment]
Checked multiple VCEP files and these features are both working - thank you! I've updated the How To guide to reflect these changes.
