### ISSUE TITLE
PAH Pilot VCEP Variation Tracker Report

### ISSUE THREAD

**Issue by dazzariti** [clingen-data-model/clinvar-google-sheets#14]
PAH should be the next VCEP to get a VCEP Variation Tracker Report, requested by Meredith Weaver

**Comment by larrybabb** [comment]
done https://docs.google.com/spreadsheets/d/1aOCdg_3YQwUf9Xrl6shJYghFvIq0N9i3QcLBjosf21A/edit#gid=0

**Comment by dazzariti** [comment]
Thank you! Just confirming - anyone who wants to refresh the sheet I'll need to add to https://console.cloud.google.com/apis/credentials/consent?project=clingen-dx - correct?

**Comment by larrybabb** [comment]
@dazzariti ^ yes.
