### ISSUE TITLE
Change "Out of Date" Alert in VCEP Variation Tracker

### ISSUE THREAD

**Issue by dazzariti** [clingen-data-model/clinvar-google-sheets#24]
We would like to change the Out of Date Alert in the VCEP Variation Tracker reports from "DateLastEvaluated > 2 years from the date of the selected ClinVar dataset." to "LP or VUS variants with a DateLastEvaluated > 2 years from the date of the selected ClinVar dataset." This would bring the Alert in line with ClinGen guidance.

Not the highest priority because we do have a workaround, which I wrote up in the Help documentation:

"Out of Date - ClinVar variants with an Expert Panel SCV with a DateLastEvaluated > 2 years from the date of the selected ClinVar dataset. Please note, ClinGen guidance requires only out of date LP and VUS classification to be reassessed every two years, if there is no discrepancy. You can filter by the “VCEP CLS” column to see only the LP and VUS classification with an “Out of Date” alert."

**Comment by dazzariti** [comment]
Include risk allele and low penetrance classifications

**Comment by dazzariti** [comment]
@larrybabb Is this a ticket I can assign to Ryan and Terry?

**Comment by larrybabb** [comment]
yes

**Comment by dazzariti** [comment]
@RyanFWebb @toneillbroad Discussed with Larry assigning this ticket to you, happy to have a quick call to review

**Comment by RyanFWebb** [comment]
Completed and ready for review.

**Comment by dazzariti** [comment]
Looks great! I spot checked 5 different reports and all looks good. Closing this ticket and updating the How to Guide. Thank you!
