### ISSUE TITLE
Variant Pathogenicity 2.0 Model

### ISSUE THREAD

**Issue by hdziadzio** [clingen-data-model/clinvar-google-sheets#31]
Revise the GK-Pilot VA ClinVar statements for VarPath, DrugResp and Other to support the simplified modeling proposals that came out of the GA4GH 2023 Spring Connect meeting. These primarily consisted of flattening the json structures ("roll-up" proposition into assertion, combine Descriptors with Value Objects).  The focus will be on getting the ClinVar GK-Pilot 2.0 version out by Plenary 2023 in the fall.

**Comment by dazzariti** [comment]
@larrybabb Is this the right repo for this ticket?

**Comment by larrybabb** [comment]
no, I think I added this here before we started combining the ga4gh git repos/issues. This should be in the gk-pilot ga4gh git repo.
