### ISSUE TITLE
Data dump of ClinVar SCVs for TDrivas/UPenn Medicine Research project

### ISSUE THREAD

**Issue by larrybabb** [clingen-data-model/clinvar-google-sheets#33]
Dump 4-30-23 clinvar BQ dataset and 'clinvar_curator.clinvar_scvs' data and share with T. Drivas for his grant project at UPenn Medicine. They will cite our work and potentially be interested in consuming the final releases once we have a production standardized pipeline.

Here's the initiating request via Anne O'Donnell

> O'Donnell, Anne <Anne.ODonnell@childrens.harvard.edu>
> Wed, May 3, 8:27 PM (7 days ago)
> to Theodore, Trust, me
> 
> Hi Teddy,
> Yeah, the person who developed the code was in the UK in a collaborator’s group (James Ware) and I suspect no longer there. That’s from my postdoc time and no one in my group has tried to use the code.
> 
> I thought ClinVar data parsing had improved some but maybe not. I’m copying Larry Babb who is a senior software engineer in Heidi’s group who works with the ClinVar data set a lot in case he has any suggestions for resources.
> 
> A lot of people also like this site: https://clinvarminer.genetics.utah.edu/ (or this is slightly out of date but I think they are working on a new version to be released soon https://simple-clinvar.broadinstitute.org/).
> 
> All the best,
> Anne
> 
> From: Drivas, Theodore <Theodore.Drivas@pennmedicine.upenn.edu>
> Date: Monday, May 1, 2023 at 5:16 PM
> To: O'Donnell, Anne <Anne.ODonnell@childrens.harvard.edu>, Odia, Trust <Trust.Odia@Pennmedicine.upenn.edu>
> Subject: Hello! And (hopefully) quick question [EXTERNAL]
> 
> * External Email - Caution *
> 
> Hi Anne!
> 
> It’s been a while, hope all is well! Hopefully I’ll get to see you at Smith again this year! Since our last Smith chat, I’ve convinced Penn to hire me and I came on as faculty here in January. Along those lines, Trust Odia, CC’ed on this email, recently joined my group as a bioinformatician. One of the projects he’ll be working on will involve the use of ClinVar data, and he’s started to look into converting the .xml files to begin extracting data from them, and we stumbled across the deprecated github repo (https://github.com/macarthur-lab/clinvar) and publication (https://www.ncbi.nlm.nih.gov/pmc/articles/PMC5473414/) that you were part of describing exactly such a process. Trust has been trying to implement it here but has had some issues with the older python version the workflow was written for and newer modules that require python 3. We know the code is no longer being maintained, but were hoping that there might be someone you know of who still uses this tool or something similar to parse the ClinVar xml data who might be able to help us out rather than having us try to reinvent the wheel and recode the conversion script ourselves 😊
> 
> Would very much appreciate any insight you might have into this, and looking forward to catching up!
> 
> Thank you!
> 
> -Teddy
>

**Comment by larrybabb** [comment]
@odiatr we can use this ticket to get the files you need sorted out.

**Comment by odiatr** [comment]
Thank you @larrybabb we are looking forward to the receiving the files.

**Comment by larrybabb** [comment]
@odiatr [Here is the folder](https://docs.google.com/document/d/1IrgGQYOFe4CZpHtHUUu_4EC64Bwyc2UWswN3WmkvURk/edit?usp=sharing) that contains the data that will get you started with the above effort. There is a "Read.me" that makes a effort at explaining its contents. I presume that once you have a chance to download and review the contents you can ask me questions.  If you can get the tables re-created in your environment that would be a great start. I am willing to help you if you get stuck and/or help after you get them set up so that you can start doing some analysis.

**Comment by larrybabb** [comment]
I am closing this ticket since the initial ticket was to deliver the data. I will open new tickets if further efforts are needed to complete the goal of getting Trust and Theodore up and running on their project.
