### ISSUE TITLE
Adjust Alert for "Newer" SCVs

### ISSUE THREAD

**Issue by dazzariti** [clingen-data-model/clinvar-google-sheets#38]
Discussed on Variant Curation June 2, 2023

Current Classification Discrepancies Alert - The following Alerts are related to a classification discrepancy between the VCEP and a non-EP submitter (with a DateLastEvaluated up to 1 year prior of EP DateLastEvaluated). 

Proposal - Update Alert so that VCEPs are only notified if newer than the EP DataLastEvaluated, not up to 1 year prior.

**Comment by dazzariti** [comment]
@RyanFWebb @toneillbroad Could I assign this to you? Happy to set up a time to answer any questions about the request.

**Comment by RyanFWebb** [comment]
Completed and ready for review.

I included non-EP submissions that were newer or posted the same day as the EP assuming they would not have been reviewed by the EP. If we'd like to exclude those submissions, we can make that change.

**Comment by dazzariti** [comment]
Reviewed several reports, all looks good, I will update the How To Guide, thank you!
