### ISSUE TITLE
Draft technical documentation for VCEP report app scripts

### ISSUE THREAD

**Issue by hdziadzio** [clingen-data-model/clinvar-google-sheets#40]
Upon completion there should be a markdown document in the repository docs folder that describes where and how the google app scripts work for the VCEP reports.

1. provide function documentation for each google appscript function. Note where these functions reside and how to access them. 
2.  provide documention on how to deploy changes to the appscript functions and consider how it will impact the existing reports.

**Comment by larrybabb** [comment]
based on last Friday's meeting, we need to have the last paragraph bulleted to show the steps for updating the sheets that are deployed. (simply reorg for easier consumption).

**Comment by larrybabb** [comment]
@RyanFWebb please create a branch for this minor change and create a PR for @toneillbroad or I to review so we can also learn more about how to do PRs going forward.

**Comment by larrybabb** [comment]
closing this - i believe it is stale or done or unneeded at this time. if we need it we will create a new ticket
