### ISSUE TITLE
Google JSON Response Exception Error when refreshing VCEP Variation Tracker

### ISSUE THREAD

**Issue by dazzariti** [clingen-data-model/clinvar-google-sheets#5]
This is the error Erin encounters when refreshing the ClinVar data in the Rett/AS VCEP Variation Tracker

![image](https://user-images.githubusercontent.com/10732982/214365673-8c3e4af1-d9d7-4217-ac95-0c2687705985.png)

**Comment by larrybabb** [comment]
erin reran and verified. no more protections for now.
